# Trigger pipeline for test deployment
deploy:webservice:
  image: curlimages/curl
  when: manual
  stage: deploy
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[INSTANCE]=test" --form "variables[COMMIT]=$CI_COMMIT_SHORT_SHA"  https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline