# define system environment variables 
cache:
  paths:
    - maven.repository/

variables:
   WAR : openSilexTestAPI
   MANAGER_ACCOUNT : phis
   MANAGER_PASS : fieldc1.61!
   MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"


build:webservice:
  image: jamesdbloom/docker-java8-maven
  stage: build
  script:
    - cd phis2-ws
    - mvn install -Ptest
  artifacts:
    paths:
    - phis2-ws/target/opensilex.war
    expire_in: 1 week