# define system environment variables 
cache:
  paths:
    - .cache/maven.repository

variables:
   REMOTE_IP : "138.102.159.37"
   WAR : openSilexTestAPI
   MANAGER_ACCOUNT : phis
   MANAGER_PASS : fieldc1.61!
   MAVEN_OPTS: "-Dmaven.repo.local=.cache/maven.repository"

before_script:
  - mkdir -p .cache/maven.repository

build:webservice:
  image: jamesdbloom/docker-java8-maven
  stage: build
  script:
    - cd phis2-ws
    - mvn install -Ptest
  artifacts:
    paths:
    - phis2-ws/target/opensilex.war
    expire_in: "1 week"
    
deploy:webservice:
  image: curlimages/curl
  stage: build
  script:
    - curl -T "phis2-ws/target/opensilex.war" "http://manager:$MANAGER_ACCOUNT@$REMOTE_IP:8080/manager/text/deploy?path=/$WAR&update=true"
  when: manual
