
variables:
   # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
   # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
   MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
   # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
   # when running from the command line.
   # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
   MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.test.skip=true"
   BUILD_WAR_PATH: "phis2-ws/target/opensilex.war"
   

before_script:
  - mkdir -p .cache/maven.repository


build:webservice:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - if [ -z "$INSTANCE" ]; then exit; fi
    - cd phis2-ws
    - mvn $MAVEN_CLI_OPTS install -Ptest
  artifacts:
    paths:
    - $BUILD_WAR_PATH
    expire_in: "1 week"
    

deploy:webservice:
  image: curlimages/curl
  when: manual
  stage: deploy
  script:
    - echo $CI_JOB_TOKEN
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "ref=master" --form "variables[INSTANCE]=test"  https://forgemia.inra.fr/api/v4/projects/403/trigger/pipeline
    